
INSERT INTO Category (id, parent_id) VALUES (-7,NULL);
INSERT INTO Category (id, parent_id) VALUES (-16,NULL);
INSERT INTO Category (id, parent_id) VALUES (-19,-16);
INSERT INTO Category (id, parent_id) VALUES (-32,NULL);
INSERT INTO Category (id, parent_id) VALUES (-35,-32);
INSERT INTO Category (id, parent_id) VALUES (-48,-32);
INSERT INTO Category (id, parent_id) VALUES (-61,NULL);
INSERT INTO Category (id, parent_id) VALUES (-64,-61);
INSERT INTO Category (id, parent_id) VALUES (-74,-32);
INSERT INTO Category (id, parent_id) VALUES (-84,-61);
INSERT INTO Category (id, parent_id) VALUES (-118,-61);
INSERT INTO Category (id, parent_id) VALUES (-142,-61);
INSERT INTO Category (id, parent_id) VALUES (-155,NULL);
INSERT INTO Category (id, parent_id) VALUES (-158,-155);
INSERT INTO Category (id, parent_id) VALUES (-168,-32);
INSERT INTO Category (id, parent_id) VALUES (-178,-32);
INSERT INTO Category (id, parent_id) VALUES (-202,-155);
INSERT INTO Category (id, parent_id) VALUES (-222,-32);
INSERT INTO Category (id, parent_id) VALUES (-235,NULL);
INSERT INTO Category (id, parent_id) VALUES (-238,-235);
INSERT INTO Category (id, parent_id) VALUES (-262,-32);
INSERT INTO Category (id, parent_id) VALUES (-287,-235);
INSERT INTO Category (id, parent_id) VALUES (-367,-32);
INSERT INTO Category (id, parent_id) VALUES (-412,-32);
INSERT INTO Category (id, parent_id) VALUES (-439,-16);
INSERT INTO Category (id, parent_id) VALUES (-540,-155);
INSERT INTO Category (id, parent_id) VALUES (-557,-32);
INSERT INTO Category (id, parent_id) VALUES (-591,-32);
INSERT INTO Category (id, parent_id) VALUES (-617,-32);
INSERT INTO Category (id, parent_id) VALUES (-627,-32);
INSERT INTO Category (id, parent_id) VALUES (-644,-61);
INSERT INTO Category (id, parent_id) VALUES (-675,-235);
INSERT INTO Category (id, parent_id) VALUES (-741,-235);
INSERT INTO Category (id, parent_id) VALUES (-846,-61);
INSERT INTO Category (id, parent_id) VALUES (-870,-61);
INSERT INTO Category (id, parent_id) VALUES (-922,-61);
INSERT INTO Category (id, parent_id) VALUES (-960,-32);
INSERT INTO Category (id, parent_id) VALUES (-998,-61);
INSERT INTO Category (id, parent_id) VALUES (-1029,-61);
INSERT INTO Category (id, parent_id) VALUES (-1039,-61);
INSERT INTO Category (id, parent_id) VALUES (-1056,-32);
INSERT INTO Category (id, parent_id) VALUES (-1136,-61);
INSERT INTO Category (id, parent_id) VALUES (-1167,-32);
INSERT INTO Category (id, parent_id) VALUES (-1177,-61);
INSERT INTO Category (id, parent_id) VALUES (-1208,-32);
INSERT INTO Category (id, parent_id) VALUES (-1274,-32);
INSERT INTO Category (id, parent_id) VALUES (-1291,-32);
INSERT INTO Category (id, parent_id) VALUES (-1308,-61);
INSERT INTO Category (id, parent_id) VALUES (-1395,-16);
INSERT INTO Category (id, parent_id) VALUES (-1440,-61);
INSERT INTO Category (id, parent_id) VALUES (-1485,-235);
INSERT INTO Category (id, parent_id) VALUES (-1731,-32);
INSERT INTO Category (id, parent_id) VALUES (-1825,-32);
INSERT INTO Category (id, parent_id) VALUES (-1842,-61);
INSERT INTO Category (id, parent_id) VALUES (-2049,-32);
INSERT INTO Category (id, parent_id) VALUES (-2302,-235);
INSERT INTO Category (id, parent_id) VALUES (-2326,-32);
INSERT INTO Category (id, parent_id) VALUES (-2628,-32);
INSERT INTO Category (id, parent_id) VALUES (-3110,-61);
INSERT INTO Category (id, parent_id) VALUES (-3623,-235);
INSERT INTO Category (id, parent_id) VALUES (-4243,-61);
INSERT INTO Category (id, parent_id) VALUES (-4488,-61);
INSERT INTO Category (id, parent_id) VALUES (-4519,-61);
INSERT INTO Category (id, parent_id) VALUES (-4931,-61);
INSERT INTO Category (id, parent_id) VALUES (-5013,-61);
INSERT INTO Category (id, parent_id) VALUES (-5072,-32);
INSERT INTO Category (id, parent_id) VALUES (-5229,-32);
INSERT INTO Category (id, parent_id) VALUES (-5400,-61);
INSERT INTO Category (id, parent_id) VALUES (-8350,-235);
update Category set created = current_timestamp;
update Category set updated = current_timestamp;
update Category set version = 1;

INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-8,'en' ,'Firing Exercises',-7);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-17,'en' ,'Wreck and grounds',-16);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-20,'en' ,'The wreck',-19);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-33,'en' ,'Light buoy',-32);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-36,'en' ,'The starboard hand light buoy',-35);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-49,'en' ,'A red light buoy',-48);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-62,'en' ,'Drifting object',-61);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-65,'en' ,'A yellow-black buoy',-64);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-75,'en' ,'The light',-74);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-85,'en' ,'A black-white light buoy',-84);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-119,'en' ,'A red light buoy',-118);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-143,'en' ,'A yellow buoy',-142);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-156,'en' ,'Radio navigation',-155);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-159,'en' ,'DGPS',-158);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-169,'en' ,'The sector light',-168);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-179,'en' ,'The port hand light buoy',-178);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-203,'en' ,'RACON',-202);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-223,'en' ,'The safe water light buoy',-222);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-236,'en' ,'Obstruction',-235);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-239,'en' ,'Diving operations',-238);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-263,'en' ,'The rear light',-262);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-288,'en' ,'Hydrographic survey',-287);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-368,'en' ,'The south cardinal light buoy',-367);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-413,'en' ,'A black-red light buoy',-412);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-440,'en' ,'Reduced depth',-439);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-541,'en' ,'AIS',-540);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-558,'en' ,'A green light buoy',-557);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-592,'en' ,'The front and rear light',-591);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-618,'en' ,'The front light',-617);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-628,'en' ,'The north cardinal buoy',-627);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-645,'en' ,'A yellow light buoy',-644);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-676,'en' ,'Cable operations',-675);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-742,'en' ,'Underwater survey',-741);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-847,'en' ,'A black-yellow-black buoy',-846);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-871,'en' ,'An object',-870);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-923,'en' ,'A yellow-black-yellow light buoy',-922);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-961,'en' ,'The mole head light',-960);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-999,'en' ,'A container',-998);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1030,'en' ,'A red-white light buoy',-1029);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1040,'en' ,'A green buoy',-1039);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1057,'en' ,'A red-white light bouy',-1056);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1137,'en' ,'A boat',-1136);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1168,'en' ,'A yellow light buoy',-1167);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1178,'en' ,'A red buoy',-1177);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1209,'en' ,'The special light buoy',-1208);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1275,'en' ,'A yellow buoy',-1274);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1292,'en' ,'The east cardinal light buoy',-1291);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1309,'en' ,'A black-yellow-black light buoy',-1308);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1396,'en' ,'Uncharted obstruction',-1395);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1441,'en' ,'A yellow-black-yellow buoy',-1440);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1732,'en' ,'A green buoy',-1731);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1826,'en' ,'The west cardinal light buoy',-1825);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1843,'en' ,'A green light buoy',-1842);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-2050,'en' ,'A red buoy',-2049);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-2303,'en' ,'light destroyed',-2302);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-2327,'en' ,'The light post',-2326);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-2629,'en' ,'A black-yellow-black buoy',-2628);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-3111,'en' ,'Logs',-3110);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-3624,'en' ,'Grenade',-3623);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-4244,'en' ,'A yellow-black light buoy',-4243);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-4489,'en' ,'A red-white buoy',-4488);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-4520,'en' ,'A black-yellow buoy',-4519);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-4932,'en' ,'A fish farm',-4931);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-5014,'en' ,'A black-yellow light buoy',-5013);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-5073,'en' ,'A black-yellow light buoy',-5072);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-5230,'en' ,'The isolated danger buoy',-5229);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-5401,'en' ,'A black-red buoy',-5400);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-8351,'en' ,'Torpedo',-8350);

