insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (0, '60', null, '', 75000, 'Nordsøen, Fanø - Sylt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-1, '61', null, '', 75000, 'Blåvands Huk - Fanø');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-2, '92', 1300, '', 360000, 'Skagerak');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-3, '93', 1044, '', 375000, 'Jyllands Vestkyst');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-4, '94', 1411, '', 130000, 'Horns Rev');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-5, '95', 1451, '', 20000, 'Grådyb');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-6, '99', null, '', 50000, 'Ringkøbing Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-7, '100', null, '', 300000, 'Kattegat');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-8, '101', 1301, '', 200000, 'Kattegat, Nordlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-9, '102', 1302, '', 200000, 'Kattegat, Sydlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-10, '103', 1303, '', 200000, 'Bælthavet');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-11, '104', null, '', 200000, 'Østersøen, Femern Bælt-Sundet');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-12, '105', 1450, '', 30000, 'Limfjorden, Ålborg - Løgstør');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-13, '106', 1382, '', 30000, 'Limfjorden, Hals - Ålborg');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-14, '107', 1383, '', 13000, 'Limfjorden, Ålborg Havn');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-15, '108', 1448, '', 65000, 'Limfjorden, Thyborøn - Mors');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-16, '109', 1449, '', 65000, 'Limfjorden, Mors - Løgstør');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-17, '110', null, '', 30000, 'Mariager Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-18, '111', 1381, '', 30000, 'Randers Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-19, '112', 1380, '', 75000, 'Århus Bugt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-20, '113', null, '', 25000, 'Horsens Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-21, '114', 1377, '', 75000, 'Farvandet nord for Fyn');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-22, '115', null, '', 20000, 'Odense Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-23, '116', null, '', 40000, 'Isefjorden');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-24, '117', null, '', 25000, 'Roskilde Fjord, Lynæs - Frederikssund');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-25, '118', null, '', 25000, 'Roskilde Fjord, Frederikssund - Roskilde');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-26, '122', null, '', 75000, 'Ålborg Bugt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-27, '123', null, '', 75000, 'Kattegat, Læsø Rende');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-28, '124', null, '', 75000, 'Kattegat, Syd for Anholt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-29, '127', 1372, '', 10000, 'Århus Havn');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-30, '128', 1379, '', 75000, 'Samsø Bælt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-31, '129', null, '', 75000, 'Kattegat, Sydøstlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-32, '131', 1331, '', 75000, 'Sundet, Nordlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-33, '132', 1332, '', 75000, 'Sundet, Sydlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-34, '133', 1333, '', 50000, 'Sundet, midterste del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-35, '134', 1334, '', 12500, 'Københavns Havn');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-36, '141', 1370, '', 75000, 'Storebælt, Nordlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-37, '142', 1368, '', 75000, 'Storebælt, Sydlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-38, '143', 1369, '', 50000, 'Storebælt, Sprogø - Langeland');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-39, '144', null, '', 20000, 'Nakskov Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-40, '145', 1371, '', 25000, 'Kalundborg Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-41, '151', 1375, '', 75000, 'Lillebælt, nordlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-42, '152', 1373, '', 75000, 'Lillebælt, Sydlige del & Farvandet syd for Fyn');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-43, '153', null, '', 25000, 'Haderslev Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-44, '154', null, '', 25000, 'Flensborg Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-45, '155', null, '', 20000, 'Als Sund og Sønderborg Bugt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-46, '157', null, '', 25000, 'Vejle Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-47, '158', 1376, '', 25000, 'Snævringen og Kolding Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-48, '159', 1374, '', 25000, 'Åbenrå Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-49, '160', null, '', 75000, 'Smålandsfarvandet, Vestlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-50, '161', null, '', 30000, 'Smålandsfarvandet, Nordøstlige del, Bøgestrømmen');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-51, '162', null, '', 30000, 'Smålandsfarvandet, Sydøstlige del, Grønsund');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-52, '163', null, '', 30000, 'Guldborg Sund');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-53, '164', null, '', 16000, 'Karrebæk Fjord');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-54, '171', null, '', 10000, 'Svendborg Sund');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-55, '172', null, '', 15000, 'Rudkøbing Løb');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-56, '188', null, '', 250000, 'Østersøen, Gedser Rev - Christiansø');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-57, '189', 1336, '', 100000, 'Bornholmsgat');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-58, '190', null, '', 50000, 'Fakse Bugt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-59, '195', null, '', 75000, 'Østersøen, Vestlige del');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-60, '196', null, '', 75000, 'Femer Bælt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-61, '197', null, '', 75000, 'Østersøen, Gedser Rev og Kadetrenden');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-62, '198', null, '', 75000, 'Østersøen, Fakse Bugt og Hjelm Bugt');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-63, 'C', null, '', 850000, 'Danmark med omgivende farvande');
insert into msi.Chart (id, chartNumber, internationalNumber, horizontalDatum, scale, name) values (-64, 'D', null, '', 850000, 'Danmark med søgrænser');
update msi.Chart set version = 1;
