
INSERT INTO Category (id, parent_id) VALUES (-7,NULL);
INSERT INTO Category (id, parent_id) VALUES (-16,NULL);
INSERT INTO Category (id, parent_id) VALUES (-61,NULL);
INSERT INTO Category (id, parent_id) VALUES (-155,NULL);
INSERT INTO Category (id, parent_id) VALUES (-235,NULL);
INSERT INTO Category (id, parent_id) VALUES (-1034,NULL);
INSERT INTO Category (id, parent_id) VALUES (-1037,-1034);
INSERT INTO Category (id, parent_id) VALUES (-32,-1037);

INSERT INTO Category (id, parent_id) VALUES (-8350,-235);
INSERT INTO Category (id, parent_id) VALUES (-3623,-235);
INSERT INTO Category (id, parent_id) VALUES (-2302,-235);
INSERT INTO Category (id, parent_id) VALUES (-1485,-235);
INSERT INTO Category (id, parent_id) VALUES (-1395,-16);
INSERT INTO Category (id, parent_id) VALUES (-1136,-61);
INSERT INTO Category (id, parent_id) VALUES (-998,-61);
INSERT INTO Category (id, parent_id) VALUES (-741,-235);
INSERT INTO Category (id, parent_id) VALUES (-675,-235);
INSERT INTO Category (id, parent_id) VALUES (-540,-155);
INSERT INTO Category (id, parent_id) VALUES (-439,-16);
INSERT INTO Category (id, parent_id) VALUES (-412,-32);
INSERT INTO Category (id, parent_id) VALUES (-367,-32);
INSERT INTO Category (id, parent_id) VALUES (-287,-235);
INSERT INTO Category (id, parent_id) VALUES (-262,-32);
INSERT INTO Category (id, parent_id) VALUES (-238,-235);
INSERT INTO Category (id, parent_id) VALUES (-222,-32);
INSERT INTO Category (id, parent_id) VALUES (-202,-155);
INSERT INTO Category (id, parent_id) VALUES (-168,-32);
INSERT INTO Category (id, parent_id) VALUES (-158,-155);
INSERT INTO Category (id, parent_id) VALUES (-74,-32);
INSERT INTO Category (id, parent_id) VALUES (-19,-16);
INSERT INTO Category (id, parent_id) VALUES (-1007,-1034);
INSERT INTO Category (id, parent_id) VALUES (-1010,-1007);
INSERT INTO Category (id, parent_id) VALUES (-1013,-1007);
INSERT INTO Category (id, parent_id) VALUES (-1016,-1007);
INSERT INTO Category (id, parent_id) VALUES (-1019,-1037);
INSERT INTO Category (id, parent_id) VALUES (-1022,-1019);
INSERT INTO Category (id, parent_id) VALUES (-1025,-1019);
INSERT INTO Category (id, parent_id) VALUES (-1028,-1019);
INSERT INTO Category (id, parent_id) VALUES (-1031,-1019);
update Category set created = current_timestamp;
update Category set updated = current_timestamp;
update Category set version = 1;

INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-8352,'da','Torpedo',-8350);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-8351,'en','Torpedo',-8350);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-3625,'da','Granat',-3623);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-3624,'en','Grenade',-3623);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-2304,'da','Fyr væltet',-2302);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-2303,'en','light destroyed',-2302);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1487,'da','Mine',-1485);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1486,'en','Mine',-1485);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1397,'da','Nyopdaget grund ',-1395);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1396,'en','Uncharted obstruction',-1395);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1138,'da','Drivende bøje',-1136);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1137,'en','Buoy adrift',-1136);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1000,'da','Drivende objekt',-998);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-999,'en','Object adrift',-998);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-743,'da','Undervandsundersøgelse',-741);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-742,'en','Underwater survey',-741);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-677,'da','Kabelarbejde',-675);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-676,'en','Cable operations',-675);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-542,'da','AIS',-540);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-541,'en','AIS',-540);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-441,'da','Reduceret vanddybde',-439);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-440,'en','Reduced depth',-439);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-414,'da','Lystønde ikke på plads',-412);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-413,'en','Light buoy off station',-412);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-369,'da','Lystønde etableret',-367);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-368,'en','Light buoy established',-367);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-289,'da','Søopmåling',-287);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-288,'en','Hydrographic survey',-287);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-264,'da','Lystønde forsvundet',-262);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-263,'en','Light buoy missing',-262);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-240,'da','Dykkerundersøgelser',-238);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-239,'en','Diving operations',-238);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-237,'da','Sejladshindring',-235);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-236,'en','Obstruction',-235);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-224,'da','Lystønde uregelmæssig',-222);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-223,'en','Light buoy unreliable',-222);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-204,'da','RACON',-202);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-203,'en','RACON',-202);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-170,'da','Lystønde inddraget',-168);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-169,'en','Light buoy withdrawn',-168);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-160,'da','DGPS',-158);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-159,'en','DGPS',-158);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-157,'da','Radionavigation',-155);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-156,'en','Radio navigation',-155);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-76,'da','Lystønde slukket',-74);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-75,'en','Light buoy unlit',-74);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-63,'da','Drivende genstand',-61);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-62,'en','Drifting object',-61);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-34,'da','Lystønde',-32);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-33,'en','Light buoy',-32);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-21,'da','Vrag',-19);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-20,'en','Wreck',-19);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-18,'da','Vrag og grunde',-16);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-17,'en','Wreck and grounds',-16);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-7,'da','Skydeøvelser',-7);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-8,'en','Firing Exercises',-7);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1008,'da','Fyr',-1007);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1009,'en','Light',-1007);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1011,'da','Fyr slukket',-1010);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1012,'en','Light unlit',-1010);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1014,'da','Fyr uregelmæssig',-1013);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1015,'en','Light unreliable',-1013);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1017,'da','Fyr ødelagt',-1016);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1018,'en','Light damaged',-1016);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1020,'da','Dagsømærke',-1019);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1021,'en','Buoy',-1019);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1023,'da','Dagsømærke forsvundet',-1022);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1024,'en','Buoy missing',-1022);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1026,'da','Dagsømærke ikke på plads',-1025);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1027,'en','Buoy off station',-1025);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1029,'da','Dagsømærke etableret',-1028);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1030,'en','Buoy established',-1028);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1032,'da','Dagsømærke inddraget',-1031);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1033,'en','Buoy withdrawn',-1031);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1035,'en','Aids to Navigation',-1034);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1036,'da','Afmærkning',-1034);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1038,'en','Floating Aids to Navigation',-1037);
INSERT INTO CategoryDesc (id, lang, name, entity_id) VALUES (-1039,'da','Flydende afmærkning',-1037);

